import type { ParsedCollection, RuleRecord, UploadedFile } from './types';

export type SourceSectionRecord = {
  key: string;
  sourceFile: string;
  hostFile: string;
  ruleCount: number;
  minRuleId?: number;
  maxRuleId?: number;
  expectedPrefix?: string;
  idRangeStatus: 'pass' | 'warning' | 'unknown';
  statusSummary: string;
};

export type CommentedRuleRecord = {
  fileName: string;
  ruleId: string;
  level?: string;
  description?: string;
  snippet: string;
};

export type GroupFlowRecord = {
  group: string;
  producedByRules: string[];
  consumedByRules: string[];
  status: 'active' | 'orphan_producer' | 'missing_producer';
};

export type RoundtripPatchSuggestion = {
  ruleId: string;
  sourceFile: string;
  sourceSection?: string;
  useCaseId: string;
  confidence: RuleRecord['useCaseConfidence'];
  insertLine: string;
  suggestedXml: string;
  placement: string;
};

export type XmlRoundtripAnalysis = {
  sourceSections: SourceSectionRecord[];
  commentedRules: CommentedRuleRecord[];
  groupFlows: GroupFlowRecord[];
  missingUseCaseSuggestions: RoundtripPatchSuggestion[];
  splitFiles: Array<{ fileName: string; ruleCount: number; xml: string }>;
  summary: {
    sourceSections: number;
    combinedFiles: number;
    commentedRules: number;
    idRangeWarnings: number;
    orphanGroups: number;
    missingGroupProducers: number;
    missingUseCaseSuggestions: number;
  };
};

const escapeRegExp = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

const extractSectionPrefix = (section?: string): string | undefined => {
  const m = section?.match(/(\d{4})[-_]/);
  return m?.[1];
};

const normalizeSectionKey = (rule: RuleRecord) => rule.sourceSection || rule.sourceFile || 'unknown-source';

const extractCommentedRules = (files: UploadedFile[]): CommentedRuleRecord[] => {
  const results: CommentedRuleRecord[] = [];
  for (const file of files) {
    const commentRe = /<!--[\s\S]*?-->/g;
    let m: RegExpExecArray | null;
    while ((m = commentRe.exec(file.content))) {
      const comment = m[0];
      if (!/<rule\b/i.test(comment)) continue;
      const ruleRe = /<rule\b[\s\S]*?<\/rule>/gi;
      let rm: RegExpExecArray | null;
      while ((rm = ruleRe.exec(comment))) {
        const block = rm[0];
        const id = block.match(/id=["']([^"']+)["']/i)?.[1] || 'unknown';
        const level = block.match(/level=["']([^"']+)["']/i)?.[1];
        const description = block.match(/<description>([\s\S]*?)<\/description>/i)?.[1]?.trim();
        results.push({ fileName: file.name, ruleId: id, level, description, snippet: block.slice(0, 2000) });
      }
    }
  }
  return results;
};

const inferExpectedPrefixStatus = (section: string, rules: RuleRecord[]) => {
  const prefix = extractSectionPrefix(section);
  if (!prefix) return { expectedPrefix: undefined, status: 'unknown' as const, summary: 'No numeric section prefix was detected.' };
  const expected = prefix.replace(/^0+/, '');
  const mismatches = rules.filter((r) => !r.id.startsWith(expected));
  if (mismatches.length === 0) return { expectedPrefix: expected, status: 'pass' as const, summary: `All rules match expected ${expected}xx range.` };
  return { expectedPrefix: expected, status: 'warning' as const, summary: `${mismatches.length} rules do not match expected ${expected}xx range.` };
};

const buildSplitXml = (section: string, rules: RuleRecord[]) => {
  const safeName = section.replace(/-->/g, '').trim() || 'reconstructed_rules.xml';
  const header = `<!--\n  Reconstructed from combined uploaded Wazuh file.\n  Source section: ${safeName}\n  Generated by Wazuh Ruleset Intelligence Platform XML Roundtrip Tools.\n-->\n<group name="reconstructed,roundtrip,">`;
  const body = rules.map((r) => r.rawXml.trim()).join('\n\n');
  return `${header}\n\n${body}\n\n</group>\n`;
};

const buildPatchSuggestion = (rule: RuleRecord): RoundtripPatchSuggestion => {
  const useCaseId = rule.useCaseId === 'unassigned' ? 'uc_todo_assign' : rule.useCaseId;
  const insertLine = `<info type="text">use_case:${useCaseId}</info>`;
  let suggestedXml = rule.rawXml;
  if (/<info\b[^>]*>\s*use_case:/i.test(rule.rawXml)) {
    suggestedXml = rule.rawXml;
  } else if (/<description>[\s\S]*?<\/description>/i.test(rule.rawXml)) {
    suggestedXml = rule.rawXml.replace(/(<description>[\s\S]*?<\/description>)/i, `$1\n  ${insertLine}`);
  } else {
    suggestedXml = rule.rawXml.replace(/(<rule\b[^>]*>)/i, `$1\n  ${insertLine}`);
  }
  return {
    ruleId: rule.id,
    sourceFile: rule.sourceFile,
    sourceSection: rule.sourceSection,
    useCaseId,
    confidence: rule.useCaseConfidence,
    insertLine,
    suggestedXml,
    placement: 'Insert immediately after <description> when available; otherwise after the opening <rule> tag.',
  };
};

export const analyzeXmlRoundtrip = (data: ParsedCollection): XmlRoundtripAnalysis => {
  const rulesBySection = new Map<string, RuleRecord[]>();
  data.rules.forEach((rule) => {
    const key = normalizeSectionKey(rule);
    rulesBySection.set(key, [...(rulesBySection.get(key) || []), rule]);
  });

  const sourceSections: SourceSectionRecord[] = [...rulesBySection.entries()].map(([section, rules]) => {
    const ids = rules.map((r) => Number(r.id)).filter(Number.isFinite);
    const status = inferExpectedPrefixStatus(section, rules);
    return {
      key: section,
      sourceFile: section,
      hostFile: rules[0]?.sourceFile || 'unknown',
      ruleCount: rules.length,
      minRuleId: ids.length ? Math.min(...ids) : undefined,
      maxRuleId: ids.length ? Math.max(...ids) : undefined,
      expectedPrefix: status.expectedPrefix,
      idRangeStatus: status.status,
      statusSummary: status.summary,
    };
  }).sort((a, b) => a.sourceFile.localeCompare(b.sourceFile));

  const produced = new Map<string, Set<string>>();
  const consumed = new Map<string, Set<string>>();
  for (const rule of data.rules) {
    for (const group of rule.groups) {
      if (!produced.has(group)) produced.set(group, new Set());
      produced.get(group)!.add(rule.id);
    }
    for (const dep of rule.dependencies) {
      if (dep.type === 'if_group' || dep.type === 'if_matched_group') {
        if (!consumed.has(dep.value)) consumed.set(dep.value, new Set());
        consumed.get(dep.value)!.add(rule.id);
      }
    }
  }
  const allGroups = new Set([...produced.keys(), ...consumed.keys()]);
  const groupFlows: GroupFlowRecord[] = [...allGroups].sort().map((group) => {
    const producedByRules = [...(produced.get(group) || new Set<string>())].sort((a,b)=>Number(a)-Number(b));
    const consumedByRules = [...(consumed.get(group) || new Set<string>())].sort((a,b)=>Number(a)-Number(b));
    const status: GroupFlowRecord['status'] = producedByRules.length === 0 ? 'missing_producer' : consumedByRules.length === 0 ? 'orphan_producer' : 'active';
    return { group, producedByRules, consumedByRules, status };
  });

  const commentedRules = extractCommentedRules(data.files);
  const missingUseCaseSuggestions = data.rules
    .filter((r) => r.useCaseConfidence !== 'confirmed')
    .map(buildPatchSuggestion)
    .sort((a, b) => Number(a.ruleId) - Number(b.ruleId));
  const splitFiles = [...rulesBySection.entries()].map(([section, rules]) => ({
    fileName: section.replace(/[^a-zA-Z0-9_.-]+/g, '_').replace(/^_+|_+$/g, '') || 'reconstructed_rules.xml',
    ruleCount: rules.length,
    xml: buildSplitXml(section, rules),
  }));

  return {
    sourceSections,
    commentedRules,
    groupFlows,
    missingUseCaseSuggestions,
    splitFiles,
    summary: {
      sourceSections: sourceSections.length,
      combinedFiles: data.files.filter((f) => (f.content.match(/Source file:/gi) || []).length > 1).length,
      commentedRules: commentedRules.length,
      idRangeWarnings: sourceSections.filter((s) => s.idRangeStatus === 'warning').length,
      orphanGroups: groupFlows.filter((g) => g.status === 'orphan_producer').length,
      missingGroupProducers: groupFlows.filter((g) => g.status === 'missing_producer').length,
      missingUseCaseSuggestions: missingUseCaseSuggestions.length,
    },
  };
};

export const buildRoundtripMarkdownReport = (data: ParsedCollection, analysis: XmlRoundtripAnalysis) => {
  const lines: string[] = [];
  lines.push('# XML Roundtrip & Parser Accuracy Report');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('## Summary');
  lines.push(`- Rules: ${data.rules.length}`);
  lines.push(`- Decoders: ${data.decoders.length}`);
  lines.push(`- Source sections: ${analysis.summary.sourceSections}`);
  lines.push(`- Combined files detected: ${analysis.summary.combinedFiles}`);
  lines.push(`- Commented/disabled rules detected: ${analysis.summary.commentedRules}`);
  lines.push(`- ID-range warnings: ${analysis.summary.idRangeWarnings}`);
  lines.push(`- Orphan producer groups: ${analysis.summary.orphanGroups}`);
  lines.push(`- Missing group producers: ${analysis.summary.missingGroupProducers}`);
  lines.push(`- Missing confirmed use-case suggestions: ${analysis.summary.missingUseCaseSuggestions}`);
  lines.push('');
  lines.push('## Source Sections');
  analysis.sourceSections.slice(0, 200).forEach((s) => lines.push(`- ${s.sourceFile}: ${s.ruleCount} rules, range ${s.minRuleId || 'n/a'}-${s.maxRuleId || 'n/a'} — ${s.statusSummary}`));
  lines.push('');
  lines.push('## Missing Group Producers');
  analysis.groupFlows.filter((g) => g.status === 'missing_producer').slice(0, 100).forEach((g) => lines.push(`- ${g.group}: consumed by ${g.consumedByRules.join(', ')}`));
  lines.push('');
  lines.push('## Orphan Producer Groups');
  analysis.groupFlows.filter((g) => g.status === 'orphan_producer').slice(0, 100).forEach((g) => lines.push(`- ${g.group}: produced by ${g.producedByRules.slice(0, 20).join(', ')}`));
  lines.push('');
  lines.push('## Use Case Info Suggestions');
  analysis.missingUseCaseSuggestions.slice(0, 200).forEach((s) => lines.push(`- Rule ${s.ruleId}: ${s.insertLine} (${s.confidence})`));
  return lines.join('\n');
};
